apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-qzyh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-qzyh
    app.kubernetes.io/part-of: test-app-tsyl
  name: devfile-sample-python-basic-qzyh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-qzyh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-qzyh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-ldlm-tenant/test-app-tsyl/devfile-sample-python-basic-qzyh@sha256:f3f4c10ea92871ca7958bd3db40bebcc43673e5dfce175c034bed2cf0f3c00d1
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
